# Numpy

Numpy is a python library that helps to do high level mathematical operations on multi dimensional array and matrices.

## Importing numpy

In [ ]:
## Import NumPy

Syntax of an array in numpy as np.array (object, dtype=None, copy=True, order='K', subok=False, ndmin=0)

```
Object:
Any object, which exposes an array interface whose __array__ method returns any nested sequence or an array.

dtype: (Optional)
This parameter is used to define the desired parameter for the array element. If we do not define the data type, then it will determine the type as the minimum type which will require to hold the object in the sequence. This parameter is used only for upcasting the array.
```

In [ ]:
# List capable of contain multiple data types but array can not contain multiple data type every element should be of single data type (homogenous data).

list_0 = [1, 1.0]                     ## List of Multiple Datatypes
list_1 = ['jay', 2, 1.9, 25, list_0]  ## List containing List
list_1
print(list_1)


# np.array (object, dtype=None)
## Create NumPy array from list [1,2,3,4] of datatype int
array_1 = ...
print(array_1)
## Create NumPy array from list [1,2,3,4] of datatype float
array_2 = ...
print(array_2)
## Create NumPy array from list [1,2,3,4] of datatype str
array_3 = 
print(array_3)

['jay', 2, 1.9, 25, [1, 1.0]]
[1 2 3 4]
[1. 2. 3. 4.]
['1' '2' '3' '4']


## List vs Array

A list cannot do mathematical operations directly, whereas an array can.
One of the key distinctions between an array and a list is this. A list can store a float or an integer, but it can't really perform mathematical operations on them.



In [ ]:
list_1 = [0,1,2]
list_1 * 2

[0, 1, 2, 0, 1, 2]

In [ ]:
list_1/3

TypeError: ignored

Of course, it's possible to do a mathematical operation with a list, but it's much less efficient.

* Arrays need to be declared. Lists don't.
* Arrays can store data very compactly and are more efficient for storing large amounts of data.

In [ ]:
arr = np.array([0,1,2])
arr * 2

array([0, 2, 4])

See how using a * (multiply) in a list returns a repeated data in the list (while we meant to multiply all of the data in the list) and where using it on an array gives a correct or desired result.

This is why you should use an array if your data requires a lot of mathematical calculations. However, you may easily add a mathematical function to your list using a numpy function.

But, you still have to use the numpy libraries anyway, so why don’t just use an array?

In [ ]:
list_1
np.multiply(list_1,2)

array([0, 2, 4])

### Advantages of using Numpy Arrays Over Python Lists:

* consumes less memory.
* fast as compared to the python List.
* convenient to use.

## Array creation in Numpy

### Creating arrays from multiple methods

In [ ]:
# Creating array from list of list [[10, 34, 35], [125, 851, 0]] with type float
float_array = 
print ("Float numbers array created from list", float_array)
 
# Creating array from tuple (5, 6, 9)
array_from_tuple = np.array()
print ("\nArray created from tuple:\n", array_from_tuple)

Float numbers array created from list [[ 10.  34.  35.]
 [125. 851.   0.]]

Array created from tuple:
 [5 6 9]


In [ ]:
# Array creation with arange, np.ones 

# Syntax. np.arrange (end value, dtype=data type)
# Create array from 0 to 4 
arrange_array= ... #arranging array by giving end value
print("arranging array from 0 to 4:\n",arrange_array)

# Syntax. np.arrange (start vaue, end value, interval, dtype=data type)
# Create array from 0 to 6 with interval of 2
arrange_array1 = ...
print("arranging array with given interval:\n",arrange_array1)

# Syntax. np.arrange (end value with data type)
# Create array till 5.0
arrange_array2=  ...
print("arranging array with given end point:\n",arrange_array2)

arranging array from 0 to 4:
 [0. 1. 2. 3.]
arranging array with given interval:
 [1 3 5]
arranging array with given end point:
 [0. 1. 2. 3. 4. 5.]


In [ ]:
# Syntax. np.ones (size of array, dtype=data type)
## Create an array (2 x 3) of all values as 1
array_with_ones= ...
print("arranging array with all ones given rows and columns:\n",array_with_ones)

# Creating a 2X3 array intialised with all zeroes
## Create an array (2 x 3) of all values as 0
array_with_zeros = ...
print ("\n Array of defined size initialized with zeros:\n", array_with_zeros)

# Create a 3X2 array intialised with all zeroes
array_with_zeros = ...
print ("\n Array of defined size initialized with zeros:\n", array_with_zeros)

arranging array with all ones given rows and columns:
 [[1. 1. 1.]
 [1. 1. 1.]]

 Array of defined size initialized with zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

 Array of defined size initialized with zeros:
 [[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
# Create an array with random values of size 3x3
Random_array = ...
print ("\n Random numbers array:\n", Random_array)


 Random numbers array:
 [[0.68240332 0.99494191 0.14987657]
 [0.21466926 0.66155306 0.13003723]
 [0.52696858 0.20573741 0.51021154]]


Rerun the above cell to see random values everytime.

In [ ]:
# List of Tuples to array

l_of_t = [(1, 2, 3), (4, 5, 6)] #Define the tuples

# Syntax. np.array (defined list of tuples)
# Create an array from l_of_t
a = ...
print(a)

[[1 2 3]
 [4 5 6]]


### linspace method

In [ ]:
#Create a sequence of 8 values in range 20 to 50
new_array = ...
print ("\nA sequential array with 8 values between"
                                        "20 and 50:\n", new_array)


A sequential array with 8 values between20 and 50:
 [20.         24.28571429 28.57142857 32.85714286 37.14285714 41.42857143
 45.71428571 50.        ]


## NumPy Array dimensions

In [ ]:
#creating a new array
array_0 = np.array([1,2,3,4])
print(array_0)
#syntax.arrayname.shape
#Each array has attributes shape (the size of each dimension)


[1 2 3 4]


(4,)

In (4,) 4 indicates that size of the array and (4,) repesents the dimension of array i.e., (4,) means 1 Dimensional array 

In [ ]:
# Creating a new array
array_1 = np.array([[1,2,3,4],[5,4,6,7],[2,3,4,6]])
print(array_1)

# Syntax.arrayname.shape
  # shape (the size of each dimension)

[[1 2 3 4]
 [5 4 6 7]
 [2 3 4 6]]


(3, 4)

In (3,4), 3 indicates that number of rows and 4 indicates number of column. and (3,4) indicates it is a 2 dimensional array

In [ ]:
# Creating a new array
array_2 = np.array([[[1,2,3,4],[5,4,6,7],[2,3,4,6]]])
print(array_2)

# Shape of an array
#syntax.arrayname.shape
   

[[[1 2 3 4]
  [5 4 6 7]
  [2 3 4 6]]]


(1, 3, 4)

In (1, 3, 4), 1 indicates the added dimension to array, remaining 3 and 4 are same as above, (1,3,4) indicates it is a 3 dimensional array

In [ ]:
# to find the data type of an array
# syntax arrayname.dtype
print("data type of array_0:\n", ...)  
print("data type of arrange_array:\n", ...) 
print("data type of array_2:\n", ...)     

data type of array_0:
 int64
data type of arrange_array:
 float64
data type of array_2:
 int64


In [ ]:
# To know the dimension of an array(1D,2D,3D etc..)
# syntax.arrayname.ndim
print("the dimension of array_0:\n", ...)
print("the dimension of array_0:\n", ...)
print("the dimension of array_0:\n", ...)  

the dimension of array_0:
 1
the dimension of array_0:
 2
the dimension of array_0:
 3


### Reshaping array

In [ ]:
# 1D to 2D and vice-versa
# Reshaping 1X6 array to 3X2 array

orig_arr_1 = np.array([10, 32, 36, 34, 4, 55]) ## 1D array

reshaped_arr_1 = orig_arr_1.reshape(3, 2)
 
print ("\nOriginal array:\n", orig_arr_1)
print ("\n Reshaped array:\n", reshaped_arr_1)
print ("\n Dimension of original array:\n", orig_arr_1.ndim)
print ("\n dimension of Reshaped array:\n", reshaped_arr_1.ndim)

orig_arr_2 = np.array([[10, 32, 36], [34, 4, 55]])   ## 2D Array
 
reshaped_arr_2 = orig_arr_2.reshape(6,)
print ("\nOriginal array:\n", orig_arr_2)
print ("\n Reshaped array:\n", reshaped_arr_2)
print ("\n dimension of original array:\n", orig_arr_2.ndim)
print ("\n dimension of Reshaped array:\n", reshaped_arr_2.ndim)


Original array:
 [10 32 36 34  4 55]

 Reshaped array:
 [[10 32]
 [36 34]
 [ 4 55]]

 Dimension of original array:
 1

 dimension of Reshaped array:
 2

Original array:
 [[10 32 36]
 [34  4 55]]

 Reshaped array:
 [10 32 36 34  4 55]

 dimension of original array:
 2

 dimension of Reshaped array:
 1


In [ ]:
# 1D to 3D and vice-versa
# Reshaping 1X4 array to 1X2X2 array
orig_arr_3 = np.array([10, 32, 36, 4])
 
reshaped_arr_3 = orig_arr_3.reshape(1 ,2, 2)

 
print ("\nOriginal array:\n", orig_arr_3)
print ("\n Reshaped array:\n", reshaped_arr_3)
print ("\n dimension of original array:\n", orig_arr_3.ndim)
print ("\n dimension of Reshaped array:\n", reshaped_arr_3.ndim)

orig_arr_4 = np.array([[[10, 32, 36], [34, 4, 55], [4,5,6]]])
 
reshaped_arr_4 = orig_arr_4.reshape(2,)  ## Reshaping is not possible
print ("\nOriginal array:\n", orig_arr_4)
print ("\n Reshaped array:\n", reshaped_arr_4)
print ("\n dimension of original array:\n", orig_arr_4.ndim)
print ("\n dimension of Reshaped array:\n", reshaped_arr_4.ndim)


Original array:
 [10 32 36  4]

 Reshaped array:
 [[[10 32]
  [36  4]]]

 dimension of original array:
 1

 dimension of Reshaped array:
 3


ValueError: ignored

In [ ]:
# Reshaping 2X4 array to 2X2X2 array
orig_arr = np.array([[10, 32, 36, 34],
                [56, 19, 75, 20]])
 
reshaped_arr = orig_arr.reshape(2, 2, 2)
 
print ("\nOriginal array:\n", orig_arr)
print ("\n Reshaped array:\n", reshaped_arr)


Original array:
 [[10 32 36 34]
 [56 19 75 20]]

 Reshaped array:
 [[[10 32]
  [36 34]]

 [[56 19]
  [75 20]]]


### Flatten array

In [ ]:
# Flatten array
arr = np.array([[1, 2, 3], [4, 5, 6]])
flarr = ...
 
print ("\nOriginal array:\n", arr)
print ("Fattened array:\n", flarr)


Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]


## Array Indexing

### Slicing

In [ ]:
array_1D = np.array([10, 32, 36, 34]) #1 Dimensonal array indexing
array_1D[...] # calling 32

32

In [ ]:
array_1D[...]   # calling 34 with negative index

34

In [ ]:
#multidimentional array indexing
array_multiD = np.array([[100, 14, 76, 54],
                [125, 81, 0, -24],
                [566, 159, 175, 20],
                [38, -47, 84, 22.0]],dtype = int)

print("Shape of the array is: ", array_multiD.ndim, array_multiD.shape)

## 81 is in the 1st row and 1st column
print("Accessing 1st row: ", array_multiD[1])
print("Accessing 1st column: ", array_multiD[:, 1])  ## : indicates all the rows
print("Accessing (1st row, 1st column): ", array_multiD[1,1])  # calling 81

Shape of the array is:  2 (4, 4)
Accessing 1st row:  [125  81   0 -24]
Accessing 1st column:  [ 14  81 159 -47]
Accessing (1st row, 1st column):  81


In [ ]:
array_multiD[3,2] # calling 84

84

In [ ]:
array_multiD[0,3] # calling 54

54

In [ ]:
## Accesing 4th row, 3rd column
array_multiD[4,3]

IndexError: ignored

In [ ]:
# An exemplar array
array_example = np.array([[10, 32, 36, 34],
                [125, 851, 0, -24],
                [56, 19, 75, 20],
                [3, -7, 4, 2.0]])

# Slicing array
## Access first 2 rows
sliced_array = array_example[:2]   #:2 returns the 0,1 indexed row
print(sliced_array)

[[ 10.  32.  36.  34.]
 [125. 851.   0. -24.]]


In [ ]:
## Access first 2 columns
sliced_array = array_example[:, :2]   #:2 (after comma) returns the 0,1 indexed column
print(sliced_array)

[[ 10.  32.]
 [125. 851.]
 [ 56.  19.]
 [  3.  -7.]]


In [ ]:
# Slicing array
sliced_array = array_example[:2, :2]   #:2 returns the 0,1 indexed row and ::2 returns the 0 and 2 nd column
print ("Array with first 2 rows and alternate"
                    "columns(0 and 2):\n", sliced_array)

Array with first 2 rows and alternatecolumns(0 and 2):
 [[ 10.  32.]
 [125. 851.]]


In [ ]:
## Accesing the 3rd row
array_example[3:] ## When accessing only row(s). Mentioning anything after : is optional. It will take all by default.

array([[ 3., -7.,  4.,  2.]])

In [ ]:
# Slicing array
## Accessing 1st, 2nd row and 2nd, 3rd column
sliced_array = array_example[1:3,2:4]
print ("1st&2nd row, 2&3rd column\n", sliced_array)

1st&2nd row, 2&3rd column
 [[  0. -24.]
 [ 75.  20.]]


### Integer array indexing

In [ ]:
# An exemplar array
array_example = np.array([[10, 32, 36, 34],
                [125, 851, 0, -24],
                [56, 19, 75, 20],
                [3, -7, 4, 2.0]])

# Integer array indexing example
Integer_index_array = array_example[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),"
                                    "(3, 0):\n", Integer_index_array)


Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [34.  0. 19.  3.]


### Boolean array indexing

In [ ]:
# An exemplar array
array_example = np.array([[10, 32, 36, 34],
                [125, 851, 0, -24],
                [56, 19, 75, 20],
                [3, -7, 4, 2.0]])

# boolean array indexing example
condition = array_example > 40 # cond is a boolean array
boolean_output = array_example[condition]
print ("\nElements greater than 40:\n", boolean_output)


Elements greater than 40:
 [125. 851.  56.  75.]


## Manipulating Arrays

In [ ]:
#Items of an array can be modified in any place of an array like below
array = np.ones((4, 5))
print("original array\n",array)

## Replace a value at 2nd row, 2nd column to 10
array[2, 2] = 10
print("modified array\n",array)

original array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
modified array
 [[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1. 10.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


In [ ]:
## Replace a value at 3rd row to 11
array[3] = 11

print(array)

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1. 10.  1.  1.]
 [11. 11. 11. 11. 11.]]


In [ ]:
## Replace a value at 1st column to -12
array[:, 1] = -12

print(array)

[[  1. -12.   1.   1.   1.]
 [  1. -12.   1.   1.   1.]
 [  1. -12.  10.   1.   1.]
 [ 11. -12.  11.  11.  11.]]


## Basic arithmetic operations

### Operations on a single array

In [ ]:
sample_arr = np.array([[5, 215, 69],
                [44, 74, 21],
                [30, 12, 94]])
 
# maximum element of array
print ("Largest element of array :", sample_arr.max())
print ("Row-wise maximum elements:",
                    sample_arr.max(axis = 1))
 
# minimum element of array
print ("Minimum element of array :", sample_arr.min())
print ("Column-wise minimum elements:",
                        sample_arr.min(axis = 0))
 
# sum of array elements
print ("Sum of all array elements:",
                            sample_arr.sum())
 
# cumulative sum along each row
print ("Cumulative sum along each row:\n",
                        sample_arr.cumsum(axis = 1))

Largest element of array : 215
Row-wise maximum elements: [215  74  94]
Minimum element of array : 5
Column-wise minimum elements: [ 5 12 21]
Sum of all array elements: 564
Cumulative sum along each row:
 [[  5 220 289]
 [ 44 118 139]
 [ 30  42 136]]


### Binary operators

In [ ]:
arr_a = np.array([[5, 7],
            [8, 1]])
arr_b = np.array([[4, 1],
            [9, 2]])
 
# addition of arrays
print ("Array sum:\n", arr_a+ arr_b)
 
# multiplication of arrays (elementwise multiplication)
print ("Array multiplication:\n", arr_a*arr_b)
 
# matrix multiplication of arrays
print ("Matrix multiplication:\n", arr_a.dot(arr_b))

NameError: ignored

## Sort Method

In [ ]:
sample_arr = np.array([[1, 4, 2],
                 [3, 4, 6],
              [0, -1, 5]])
 
# sorted array
print ("Array elements in sorted order:\n",
                    np.sort(sample_arr, axis = None))
 
# sort array row-wise
print ("Row-wise sorted array:\n",
                np.sort(sample_arr, axis = 1))

Array elements in sorted order:
 [-1  0  1  2  3  4  4  5  6]
Row-wise sorted array:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]


In [ ]:
# Example to show sorting of structured array
# set alias names for dtypes
dtypes = [('name', 'S10'), ('graduation_year', int), ('Percentage', float)]
 
# Values to be put in array
values = [('Kartik', 2001, 96.5), ('Pranay', 2001, 85.7),
           ('Arjav', 1999, 76.9), ('Krunal', 2003, 90.0)]
            
# Creating array
created_arr = np.array(values, dtype = dtypes)
print ("\nArray sorted by names:\n",
            np.sort(created_arr, order = 'name'))

[(b'Kartik', 2001, 96.5) (b'Pranay', 2001, 85.7) (b'Arjav', 1999, 76.9)
 (b'Krunal', 2003, 90. )]

Array sorted by names:
 [(b'Arjav', 1999, 76.9) (b'Kartik', 2001, 96.5) (b'Krunal', 2003, 90. )
 (b'Pranay', 2001, 85.7)]


## Data Type

In [ ]:
import numpy as np

#create array with data type integer
arr = np.array([3, 6, 0, -1], dtype='i')
print(arr.dtype)

int32


In [ ]:
#coverting datatype of existing array
converted_arr = arr.astype('bool')
print(arr)
print(converted_arr.dtype)
print(converted_arr)

[ 3  6  0 -1]
bool
[ True  True False  True]


## numpy array join

In [ ]:
import numpy as np

arr_concat1 = np.array([2, 2, 6, 8])
arr_concat2 = np.array([1, 3, 5, 7])
final_arr = np.concatenate((arr_concat1, arr_concat2))
print("1d concatenated array : \n",final_arr)


#joining a 2D array
arr2d_concat1 = np.array([[3, 5], [7, 9]])
arr2d_concat2 = np.array([[0, 6], [2, 1]])
arr_concat_final = np.concatenate((arr2d_concat1, arr2d_concat2), axis=1)
print("\n 2d concatenated array: \n",arr_concat_final)

1d concatenated array : 
 [2 2 6 8 1 3 5 7]

 2d concatenated array: 
 [[3 5 0 6]
 [7 9 2 1]]


## numpy array search

In [ ]:
# find the indexes where values are odd
import numpy as np

arr_all = np.array([123, 345, 29, 24, 80, 61, 79, 84])

arr_odd_index = np.where(arr_all%2 == 1)

print(arr_odd_index)

(array([0, 1, 2, 5, 6]),)


## numpy array split

### Split Array function

In [ ]:
import numpy as np

array_to_split = np.array([6, 1, 7, 9, 10, 4, 43, 28])

split_array = np.array_split(array_to_split , 3)

print(split_array[0])
print(split_array[1])
print(split_array[2])

[6 1 7]
[ 9 10  4]
[43 28]


### Horizontal Split

In [ ]:
import numpy as np
  
array = np.arange(27.0).reshape(3, 3, 3)
  
hsplit_arr = np.hsplit(array, 1)
print("Array before splitting : \n", array)
print("\n Array after horizontal split : \n ",hsplit_arr)

### Vertical Split

In [ ]:
import numpy as np
  
array = np.arange(36.0).reshape(6, 6)
  
vsplit_arr = np.vsplit(array, 2)
  
print("Array before splitting : \n", array)
print("\n Array after vertical split : \n",vsplit_arr)

## Numpy Stacking

In [ ]:
import numpy as np
  
arr_1 = np.array([[7, 3],
              [1, 4]])
  
arr_2 = np.array([[1, 9],
              [4, 0]])

### Vertical Stacking



In [ ]:
# vertical stacking
print("Vertical stacking:\n", np.vstack((arr_1, arr_2)))

Vertical stacking:
 [[7 3]
 [1 4]
 [1 9]
 [4 0]]


### Horizontal Stacking

In [ ]:
# horizontal stacking
print("\nHorizontal stacking:\n", np.hstack((arr_1, arr_2)))


Horizontal stacking:
 [[7 3 1 9]
 [1 4 4 0]]


### Column Stacking

In [ ]:
column = [5, 6]
  
# stacking columns
print("\nColumn stacking:\n", np.column_stack((arr_1, column)))


Column stacking:
 [[7 3 5]
 [1 4 6]]


## Broadcasting

Broadcasting is the ability of a of NumPy to treat arrays of different shapes during arithmetic operations.
If two arrays are of exactly the same shape, then these operations are smoothly performed.


In [ ]:
a = np.array([1,2,3,4]) 
b = np.array([1,80,33,44]) 
c = a * b 
print("multiplication of the two arrays",c)

multiplication of the two arrays [  1 160  99 176]


If two or any set of arrays brodcastable then they are atleast follow any one of the following rules.
1. Arrays have exactly the same shape.
2. Arrays have the same number of dimensions and the length of each dimension is either a common length or 1.
3. Arrays having too few dimensions can have their shape prepended with a dimension of length 1 so that the above-stated property is true.

In [ ]:
# Rule 1 - Passed
a = np.array([5, 11, 25,54])
b = np.array([5, 5, 5, 63])
c = a + b
print("adding two arrays",c)

adding two arrays [ 10  16  30 117]


In [ ]:
# Rule 1 - Failed
# Rule 2 - Failed
a = np.array([5, 11, 25,54])
b = np.array([5, 5, 5])
c = a + b
print("adding two arrays",c)

ValueError: ignored

In [ ]:
# Rule 1 - Failed
# Rule 2 - Pass
a + 5  ## 5 is scalar value and defult of dimension 1

array([10, 16, 30, 59])

### Scalar operation on an array


In this example, the scalar is stretched to become an array of with the same shape as a so the shapes are compatible for element-by-element multiplication

In [ ]:

import numpy as np
  
array = np.array([5, 6, 7])
  
# Example 1
scalar = 2.0
print("output of scalar multiplication : ", scalar * array)
  
# Example 2
array_2 = [2.0, 2.0, 2.0]
print("output on arrays multiplication :",array * array_2)

output of scalar multiplication :  [10. 12. 14.]
output on arrays multiplication : [10. 12. 14.]


We can similarly extend this to arrays of higher dimensions. Observe the result when we add a one-dimensional array to a two-dimensional array:

In [ ]:
a = np.array([0, 1, 2])
M = np.ones((3, 3))
print("output of array addition :",M+a)

output of array addition : [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


### Broadcasting where both arrays gets stretched

In below example, broadcasting stretches both arrays to form an output array larger than either of the initial arrays

np.newaxis is used to increase the dimension of the existing array by one more dimension when used once. Thus,

1D array will become 2D array.2D to 3D

In [ ]:
a = np.arange(3)
b = np.arange(2)[:, np.newaxis] #it is equal to b.reshape(2,1) 
a+b


array([[0, 1, 2],
       [1, 2, 3]])

In [ ]:
import numpy as np
  
a = np.array([5.0, 12.0, 42.0, 75.0])
b = np.array([1.0, 6.0, 8.0])
  
print(a[:, np.newaxis] + b)

[[ 6. 11. 13.]
 [13. 18. 20.]
 [43. 48. 50.]
 [76. 81. 83.]]


<img src='https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png' />

The lightboxes represent the broadcasted values: again, this extra memory is not actually allocated in the course of the operation, but it can be useful conceptually to imagine that it is.